# Custom Language File for Launcher Customizer

[ejs.app]
title = "cocomo"

[ejs.landing]
mediaGitHubURL = "https://github.com/olleh33/cocomo"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/a5kwVx6k5x"

[ejs.settings]
sourceGithubLink = "https://github.com/olleh33/cocomo"
supportLink = "https://github.com/olleh33/cocomo/issues"

[ejs.welcome]
welcomeHeader = "코코모 월드에 오신 것을 환영합니다."
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
